---
openapi: 3.0.1
info:
  title: Test Tripla API V1
  version: v1
  description: API documentation for Test Tripla application
paths:
  "/api/v1/health":
    get:
      summary: Health check endpoint
      tags:
      - Health
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  timestamp:
                    type: string
                  version:
                    type: string
                  database:
                    type: string
servers:
- url: http://localhost:3000
  description: Development server
