---
openapi: 3.0.1
info:
  title: Test Tripla API V1
  version: v1
  description: API documentation for Test Tripla application
paths:
  "/api/v1/follow/{followed_id}":
    post:
      summary: Follow a user
      tags:
      - Follows
      parameters:
      - name: X-User-ID
        in: header
        required: true
        description: Current user ID
        schema:
          type: string
      - name: followed_id
        in: path
        required: true
        description: ID of the user to follow
        schema:
          type: integer
      responses:
        '201':
          description: followed successfully
        '404':
          description: user to follow not found
        '401':
          description: unauthorized
  "/api/v1/unfollow/{followed_id}":
    delete:
      summary: Unfollow a user
      tags:
      - Follows
      parameters:
      - name: X-User-ID
        in: header
        required: true
        description: Current user ID
        schema:
          type: string
      - name: followed_id
        in: path
        required: true
        description: ID of the user to unfollow
        schema:
          type: integer
      responses:
        '200':
          description: unfollowed successfully
        '404':
          description: user to unfollow not found
        '401':
          description: unauthorized
  "/api/v1/followers":
    get:
      summary: Get list of followers for current user
      tags:
      - Follows
      parameters:
      - name: X-User-ID
        in: header
        required: true
        description: Current user ID
        schema:
          type: string
      responses:
        '200':
          description: followers list returned
        '401':
          description: unauthorized
  "/api/v1/following":
    get:
      summary: Get list of users current user is following
      tags:
      - Follows
      parameters:
      - name: X-User-ID
        in: header
        required: true
        description: Current user ID
        schema:
          type: string
      responses:
        '200':
          description: following list returned
        '401':
          description: unauthorized
  "/api/v1/health":
    get:
      summary: Health check endpoint
      tags:
      - Health
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  timestamp:
                    type: string
                  version:
                    type: string
                  database:
                    type: string
  "/api/v1/sleep_records":
    post:
      summary: Create a new sleep record (Clock In)
      tags:
      - Sleep Records
      parameters:
      - name: X-User-ID
        in: header
        required: true
        schema:
          type: string
      responses:
        '201':
          description: sleep record created
        '400':
          description: bad request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sleep_at:
                  type: string
                  format: date-time
              required:
              - sleep_at
    get:
      summary: List all sleep records for the current user
      tags:
      - Sleep Records
      parameters:
      - name: X-User-ID
        in: header
        required: true
        description: Current user ID
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    user_id:
                      type: integer
                    sleep_at:
                      type: string
                    wake_at:
                      type: string
                      nullable: true
                    created_at:
                      type: string
                    updated_at:
                      type: string
        '401':
          description: unauthorized
  "/api/v1/sleep_records/{id}":
    patch:
      summary: Update a sleep record with wake time (Clock Out)
      tags:
      - Sleep Records
      parameters:
      - name: X-User-ID
        in: header
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
        style: simple
      responses:
        '200':
          description: wake_at updated
        '404':
          description: not found
servers:
- url: http://localhost:3000
  description: Development server
